### ISSUE TITLE
Mailsubjects with UTF-8 Characters are broken

### ISSUE THREAD

**Issue by StefanSchubert** [gessnerfl/fake-smtp-server#28] opened 2020-03-20 20:07 UTC
Hi there! 

1st thanks a lot for this server. I have been using it for dev purposes in some projects by now.

One of my last projects howerver is building UTF-8 Subjects, like described here:
https://stackoverflow.com/questions/20806154/php-mail-special-characters-in-subject-field

Which are displayed properly in real mail clients but are broken in fake-servers GUI.
To support aceptance tests, it would be nice if this server could handle this, too.

Cheers
Stefan

**Comment by gessnerfl** [comment] 2020-03-21 19:29
@StefanSchubert I tried to reproduce this. UTF-8 characters are properly rendered. 
Can you maybe provide an example? Are you requesting support of HTML encoding (e.g. `&starf`)?

**Comment by StefanSchubert** [comment] 2020-03-21 21:58
Hi,

sure - here is a screenshot:



The same Mailsubject ist being displayed correctly e.g. in outlook.
In this example the subject does not even contain utf-8 characters, but has been formated to be interpreted like utf-8.
In case we have subjects containing äöüß the display ist very worse.

Im using the docker version with tag 1.4.0 if this helps.

Kind regrads
Stefan

**Comment by gessnerfl** [comment] 2020-03-23 19:39
@StefanSchubert 
I'm still not able to reproduce the issue

I tested with an HTML mail containing UTF8 characters and also HTML4 encoding. 

Subject: `Test-Plain-Mail äöü &starf; &pound; \u03A3 \u03A8 20`
Content: `This is the test mail number äöü &starf; &pound; \u03A3 \u03A8 20``

The result looks the same for me in FakeSMTPServer UI as well as in Outlook:

<img width="1413" alt="Screenshot 2020-03-23 at 20 32 56" src="https://user-images.githubusercontent.com/6311334/77355954-b2504f00-6d45-11ea-855d-0fbef9207264.png">

<img width="723" alt="Screenshot 2020-03-23 at 20 36 48" src="https://user-images.githubusercontent.com/6311334/77356308-5803be00-6d46-11ea-879e-54c24f267578.png">

I need more details to be able to reproduce and fix the issue

**Comment by gessnerfl** [comment] 2020-03-23 19:51
Just to confirm I tested this from my development environment and also with the latest docker image 1.4.0. For both I get the same results.

**Comment by StefanSchubert** [comment] 2020-03-23 20:08
Please close the case, we saw that by removing  

// https://stackoverflow.com/questions/20806154/php-mail-special-characters-in-subject-field
$subject = '=?UTF-8?q?' . quoted_printable_encode($maildata["subject"]) . '?=';
the special Subject encoding lead to a proper display of the subject. As the used library to send the email already does some encoding.
Seemed to be a problem with double encoding on our site.

Sorry for any inconvenience caused.
Stay healthy and thanks a lot for quick support.

Stefan

**Comment by gessnerfl** [comment] 2020-03-24 07:06
Closing Issue as requested

**Closed by gessnerfl** 2020-03-24 07:06 UTC
