### ISSUE TITLE
Sending css with HTML emails also affect the Fake SMTP Server's UI

### ISSUE THREAD

**Issue by MarioMatschgi** [gessnerfl/fake-smtp-server#85] opened 2022-08-17 10:38 UTC
We send HTML-Emails from a C# backend and discovered, that if we have any css in it, for example with the <link> or <style> tags, that those styles also affect the UI of the Fake SMTP Server.

Here is an example:
![image](https://user-images.githubusercontent.com/46848943/185098554-3f284437-853f-4197-a8f8-adf75f43710d.png)

The Email is a multipart (html) email, which has a <style> tag, that has the following css:
```
body {
  color: green;
  font-size:30px;
}
```

As you can see, those styles affect the GUI and not just the email content

Hope this helps,
if you need any more information, feel free to contact me :)

**Comment by gessnerfl** [comment] 2022-08-18 18:55
HI @MarioMatschgi ,

I can reproduce the issue locally and will provide a fix soon. The problem here is that HTML mails need to be encapsulated to avoid that embedded styles effect the page style. Will wrap them into iframes to ensure that the style is only applied for the iframe content.

**Comment by MarioMatschgi** [comment] 2022-08-18 19:00
> HI @MarioMatschgi ,
> 
> I can reproduce the issue locally and will provide a fix soon. The problem here is that HTML mails need to be encapsulated to avoid that embedded styles effect the page style. Will wrap them into iframes to ensure that the style is only applied for the iframe content.

Thank you so much - very much appreciated :) ❤️

**Comment by gessnerfl** [comment] 2022-09-03 19:58
@MarioMatschgi  this should be fixed with version 1.10.0 which is now available

**Comment by MarioMatschgi** [comment] 2022-09-03 20:01
> @MarioMatschgi  this should be fixed with version 1.10.0 which is now available

Wow, thank you so much!
I will try it when I get the time to do so :)

You're awesome, hope you have a great day!

**Comment by gessnerfl** [comment] 2023-03-12 09:05
Closing issue. No response received. Issue seems to be fixed.

**Closed by gessnerfl** 2023-03-12 09:05 UTC
Labels: bug
