### ISSUE TITLE
This line is giving problems when deploying in jeslatic's containers

### ISSUE THREAD

**Issue by mplescano** [gessnerfl/fake-smtp-server#23] opened 2019-12-26 02:16 UTC
https://github.com/gessnerfl/fake-smtp-server/blob/6c0fac1254eec69d70f4e25f88fc6cc3c2236d59/Dockerfile#L12

This is working for me
ENTRYPOINT ["/opt/java/openjdk/bin/java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /opt/fake-smtp-server.jar" ]

**Comment by gessnerfl** [comment] 2019-12-26 15:55
@mplescano: what kind of issue are you facing? Is the container not starting resp. is the Java application blocked e.g. at startup?

Adding the JVM option `-Djava.security.egd=file:/dev/./urandom` changes the default random generator on Unix based systems from `/dev/random` to `/dev/urandom`. In contrast to `/dev/random` `/dev/urandom` is not blocking even if it is e.g. running out of entropy. 

I will prepare the change. However it would be good first to understand the root cause.

**Comment by gessnerfl** [comment] 2019-12-26 16:52
Already figured out what is causing the issue. An entry point with `sh -c` is not catching e.g. a graceful shutdown.
Will change it to user `ENTRYPOINT exec ...`. This should fix the issue.

**Comment by gessnerfl** [comment] 2019-12-26 17:10
@mplescano  The issue should be fixed with release 1.3.0. Can you please retry and provide feedback if the issue is also fixed on Jelastic Platform?

**Comment by mplescano** [comment] 2019-12-31 02:50
It's not running now in my jelastic platform.
this line now is the culprit
FROM amazoncorretto:11.0.5

Before to the change this was working
FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.3_7

Logs:
Node ID : XXXXX
-----------------------
The [ jem docker update ] operation has failed: The selected image is based on non-supported OS template

**Comment by gessnerfl** [comment] 2020-01-01 10:48
@mplescano Can you please retry with version 1.3.1
I changed back the base image to adoptopenjdk which is based on alpine linux. I guess jelastic is not supporting amazon linux as base image. This was used by the amazoncorretto base image.

**Comment by gessnerfl** [comment] 2020-02-18 18:52
closing the ticket after more than one month inactivity. Assuming the fix of version 1.3.1 solved the issue

**Closed by gessnerfl** 2020-02-18 18:52 UTC
Labels: bug
