### ISSUE TITLE
if behind reverse proxy attachements are not working 

### ISSUE THREAD

**Issue by Stef4nBr** [gessnerfl/fake-smtp-server#526] opened 2024-07-29 15:33 UTC
Hello, I am running fake-smtp-server as a docker container behind reverse proxy ( apache ).
In order to get it running I specified:
   
```
 environment:
      - SERVER_SERVLET_CONTEXTPATH=/fake-smtp-server
```
Most of the application is working fine but attachments are pointing for example www.example.eu/api/emails/3/attachments/3 does ignoring my proxy mapping.
Can you pls update the code so it takes this into account? : 
https://github.com/gessnerfl/fake-smtp-server/blob/main/webapp/src/components/email/email-attachment-panel.tsx

Also its happening for each href= property like favicon & logo 
https://github.com/gessnerfl/fake-smtp-server/blob/main/webapp/index.html 

![fakeSmtpBug](https://github.com/user-attachments/assets/496f5425-7c69-4031-81a0-3dbb081b0195)

**Comment by gessnerfl** [comment] 2024-07-30 19:28
@Stef4nBr it seems that support for reverse proxy got broken with the migration of the build tool to vite.

**Comment by gessnerfl** [comment] 2024-08-04 19:15
@Stef4nBr this issue should be resolved with the upcoming version 2.4.0. Can you please retest and close the ticket if the issue is resolved.

**Comment by Stef4nBr** [comment] 2024-08-06 07:10
Hi @gessnerfl thank you for quick response, just pulled 2.4.0 docker image and retested the issue:
All upper mentioned href's are pointing correctly to attachments , logo , fav-icon 
Issue is not reproducible anymore.

**Comment by Stef4nBr** [comment] 2024-08-06 07:11
Issue is not reproducible anymore.

**Closed** 2024-08-06 07:10 UTC
Labels: bug
