### ISSUE TITLE
Docker image 500 internal server error on web interface

### ISSUE THREAD

**Issue by Karql** [gessnerfl/fake-smtp-server#172] opened 2023-05-10 08:58 UTC
Hi!

I have tried to use docker image for `v2`.

`docker-compose.yml`

```
version: '3'

services:
  fake-smtp-server:
    image: gessnerfl/fake-smtp-server:2.0.2
    hostname: "fake-smtp-server"
    restart: always
    environment:
      #The SMTP Server Port used by the Fake SMTP Server
      FAKESMTP_PORT: 5025
      #Port of the web interface
      SERVER_PORT: 5080
      #Port of the http management api
      MANAGEMENT_SERVER_PORT: 5081
    ports:
      - 5025:5025      #expose smtp port
      - 5080:5080      #expose web ui
      - 5081:5081      #expose management api      
```

After running it and open `http://localhost:5080/`

There is an error:

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/97cf064b-60af-470a-b86a-585f7a29c5d9)

Logs:

```
2023-05-10T08:52:06.879Z ERROR 1 --- [nio-5080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers
        at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
        at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372) ~[thymeleaf-spring6-3.1.1.RELEASE.jar:3.1.1.RELEASE]
        at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192) ~[thymeleaf-spring6-3.1.1.RELEASE.jar:3.1.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1415) ~[spring-webmvc-6.0.8.jar:6.0.8]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1159) ~[spring-webmvc-6.0.8.jar:6.0.8]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1098) ~[spring-webmvc-6.0.8.jar:6.0.8]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.8.jar:6.0.8]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.8.jar:6.0.8]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.8.jar:6.0.8]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.8.jar:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.8.jar:6.0.8]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.8.jar:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:91) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

When container starting there is also a warn:
`2023-05-10T08:48:57.916Z  WARN 1 --- [           main] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates, check your Thymeleaf configuration, or set spring.thymeleaf.check-template-location=false)`

btw.

swagger is working for `GET /api/meta-data`

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/c71df7d0-c1b4-4097-8c38-b4dec38af0b4)

but for `GET /api/emails` there is also error 500

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/8bf06217-4d62-4e19-bcae-12499e64d7b6)

```
2023-05-10T08:55:43.897Z ERROR 1 --- [nio-5080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.data.mapping.PropertyReferenceException: No property 'string' found for type 'Email'] with root cause

org.springframework.data.mapping.PropertyReferenceException: No property 'string' found for type 'Email'
```

Best regards,
Mateusz

**Comment by Karql** [comment] 2023-05-10 13:50
Thank you @etidahouse I have missed this.

Maybe it should be tweaked a bit, because this is a default payload in swagger 😉

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/a05512e9-badd-4614-9647-071ac68273eb)

So REST API works correctly but main problem still occurs - Web UI not working at all.

**Comment by etidahouse** [comment] 2023-05-10 15:46
@Karql 

I have pull the image, by default, the Web UI is deployed at `http://localhost:3000/`

I will try to do a PR to fix this in the `README.md` and correct the value for the `sort` parameter in Swagger

**Comment by Karql** [comment] 2023-05-10 17:43
Port 3000? I can not see any 3000 open.

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/1e76f739-b502-4ac7-a0a5-911de9f38147)

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/2a1e0dfe-f1f5-42e2-9bb6-c0edc50a7eb2)

In previous version e.g. `1.10.4` default port was `5080`.
I have found that this port was changed to `8080` in  https://github.com/gessnerfl/fake-smtp-server/issues/139 

So I have tried to change it using env variable `SERVER_PORT: 5080`.

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/820faf36-d32b-4d4b-810e-6d5efd4fb80f)

This works as expected but something is worng with UI itself.

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/d2118048-b6ad-41c4-80ca-8f2ae8a543cd)

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/fa96a6af-b259-4e54-a470-2d047fd56f86)

**Comment by Karql** [comment] 2023-05-10 18:22
Ok I have found that you need to explicitly include `index.html` in url.

http://localhost:5080/index.html

There is no redirect.

But anyway react ui application wont boot up and shows blank page:

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/3d1641df-57b1-4340-a5a8-015b226dc4e7)

**Comment by isen-ng** [comment] 2023-05-21 16:14
It only started working when I reverted back to 2.0.0

This commit broke the container:
https://github.com/gessnerfl/fake-smtp-server/pull/151/files

**Comment by gessnerfl** [comment] 2023-05-27 18:22
I crosschecked it and I think that the issue is related to how JIB is building the docker image. Will further investigate how to fix it.

**Comment by gessnerfl** [comment] 2023-05-28 19:29
This issue should be fixed with version 2.0.3. @Karql can you please cross check?

**Comment by Karql** [comment] 2023-05-29 04:20
@gessnerfl looks ok now 👌

![image](https://github.com/gessnerfl/fake-smtp-server/assets/173098/6881fca8-fcad-4d3b-a4e2-4a182a4b80af)

**Closed** 2023-05-29 18:08 UTC
Labels: bug
